apiVersion: v1
kind: PersistentVolume
metadata:
  name: mon-super-pv1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    # le chemin vers le stockage cible
    path: /tmp
    server: 172.17.0.2
