apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-demo
# un storage backend qui peut provisioner des pv
# ici 
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4