apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.namet1 }}
  labels:
    name: {{ .Values.label }}
spec:
  containers:
  - name: {{ .Values.container.name }}
    image: {{ .Values.container.image }}
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: {{ .Values.container.port }}
